services:
  postgres:
    image: postgres:16
    container_name: go-auth-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go_auth
    ports:
      - "5432:5432"
    volumes:
      - pgdata_go_auth:/var/lib/postgresql/data

volumes:
  pgdata_go_auth:
